{{- if .Values.persistentVolumeClaims.media.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.persistentVolumeClaims.media.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaims.media.storageSize }}
  volumeName: {{ .Values.persistentVolumeClaims.media.existingVolumeName | quote }}
  storageClassName: {{ .Values.persistentVolumeClaims.media.storageClassName | quote }}
{{- end }}

{{- if .Values.persistentVolumeClaims.config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.persistentVolumeClaims.config.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaims.config.storageSize }}
  volumeName: {{ .Values.persistentVolumeClaims.config.existingVolumeName | quote }}
  storageClassName: {{ .Values.persistentVolumeClaims.config.storageClassName | quote }}
{{- end }}
