# Default values for openshift-gitops-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
