# Default values for quay-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  channel: stable-3.9
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
