# Default values for keycloak-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  channel: fast
  installPlanApproval: Automatic
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
