# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "satisfactory.fullname" . }}-config
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 30Gi
#   storageClassName: "lvms-vg1"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "satisfactory.fullname" . }}-backups
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.backups.size | quote }}
  storageClassName: {{ .Values.storage.backups.storageClassName | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "satisfactory.fullname" . }}-gamefiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.gamefiles.size | quote }}
  storageClassName: {{ .Values.storage.gamefiles.storageClassName | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "satisfactory.fullname" . }}-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.logs.size | quote }}
  storageClassName: {{ .Values.storage.logs.storageClassName | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "satisfactory.fullname" . }}-saved
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.saved.size | quote }}
  storageClassName: {{ .Values.storage.saved.storageClassName | quote }}
