apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.modpack.slug }}-env
  namespace: {{ .Release.Namespace }}
  labels: {}
data:
  VERSION: {{ .Values.server.version | quote }}
  MEMORY: {{ .Values.server.memory | quote }}
  MOTD: {{ .Values.server.motd | quote }}
  # WHITELIST_FILE: /extras/whitelist.json
  # OPS_FILE: /extras/ops.json
  {{- include "minecraft.modpack.env" . | nindent 2 }}
  {{- include "minecraft.modpack.extraEnv" . | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.modpack.slug }}-server-files
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "*.json").AsConfig | indent 2 }}
